// <auto-generated />
using System;
using DemoWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoShared.Models.Entities.AccountModel", b =>
                {
                    b.Property<string>("emp_no")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("EMP_NO");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("CRE_DT");

                    b.Property<string>("email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("password")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PASSWORD");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPD_DT");

                    b.Property<string>("user_id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USR_ID");

                    b.HasKey("emp_no");

                    b.ToTable("m_account");
                });

            modelBuilder.Entity("DemoShared.Models.Entities.AppRolesModel", b =>
                {
                    b.Property<string>("app_role_id")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ROLE_ID");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("CRE_DT");

                    b.Property<string>("description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPD_DT");

                    b.HasKey("app_role_id");

                    b.ToTable("m_app_roles");
                });

            modelBuilder.Entity("DemoShared.Models.Entities.CompanyModel", b =>
                {
                    b.Property<string>("company_id")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("CPN_ID");

                    b.Property<string>("company_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CPN_NAME");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("CRE_DT");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPD_DT");

                    b.HasKey("company_id");

                    b.ToTable("m_company");
                });

            modelBuilder.Entity("DemoShared.Models.Entities.EmpRoleMappingsModel", b =>
                {
                    b.Property<string>("emp_no")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("EMP_NO");

                    b.Property<string>("app_role_id")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ROLE_ID");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("CRE_DT");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPD_DT");

                    b.HasKey("emp_no", "app_role_id");

                    b.ToTable("m_emp_role_mappings");
                });

            modelBuilder.Entity("DemoShared.Models.Entities.EmployeesModel", b =>
                {
                    b.Property<string>("emp_no")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("EMP_NO");

                    b.Property<DateTime?>("birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<string>("company_id")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("CPN_ID");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("CRE_DT");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CRE_BY");

                    b.Property<string>("emp_name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("USR_NAME");

                    b.Property<string>("emp_name_kana")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("USR_NAME_KATA");

                    b.Property<DateTime?>("hire_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("HIRE_DATE");

                    b.Property<string>("is_retired")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("RETIED");

                    b.Property<string>("post_cd")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("POST_CD");

                    b.Property<string>("sex")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("SEX");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPD_DT");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPD_BY");

                    b.HasKey("emp_no");

                    b.ToTable("m_employees");
                });
#pragma warning restore 612, 618
        }
    }
}
